# build and test on linux, windows, mac with node 12,14
name: Test

on:
  push:
    branches:
      - master
      - beta
  pull_request:
    branches:
      - master
      - beta

jobs:
  test:
    env:
      CI: true
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [12.x, 14.x]
        test-name-pattern: [
          "javascript npm",
          "javascript pnpm",
          "javascript yarn ",
          "javascript yarn2",
          "typescript npm",
          "typescript pnpm",
          "typescript yarn ",
          "typescript yarn2",
          "svite hmr-test"
        ]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm i -g pnpm
      - run: echo "testing ${{matrix.test-name-pattern}}"
      - run: npm test  --scripts-prepend-node-path -- --testNamePattern="${{matrix.test-name-pattern}}"
      - name: archive test/temp directory
        if: failure()
        shell: bash
        run: tar -cvf test-temp.tar --exclude="node_modules" --exclude=".yarn" --exclude="dist" --exclude=".pnp.js" test/temp/
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: test-temp-${{ matrix.os }}-${{ matrix.node-version }}-${{ matrix.test-name-pattern }}
          path: |
            test-temp.tar
            test/temp/jest-results.json
            test/temp/junit.xml
      - uses: actions/upload-artifact@v2
        if: success()
        with:
          name: test-results-${{ matrix.os }}-${{ matrix.node-version }}-${{ matrix.test-name-pattern }}
          path: |
            test/temp/jest-results.json
            test/temp/junit.xml
